### ISSUE TITLE
Phoenix 1.3 Test

### ISSUE THREAD

**Issue by Teifion** [kagux/ex_debug_toolbar#26]
I upped the version in mix.exs to 0.3.0 and gave it a spin!

It compiled but when I went to load a page I got the following error after the page load (the page itself loaded fine as if the toolbar wasn't included at all).

```
12:07:23.802 [error] an exception was raised:
    ** (ArgumentError) argument error
        :erlang.convert_time_unit(nil, :native, :micro_seconds)
        (ex_debug_toolbar) web/views/helpers/time_helpers.ex:6: ExDebugToolbar.View.Helpers.TimeHelpers.native_time_to_string/1
        (ex_debug_toolbar) web/templates/toolbar/show/ecto/_queries.html.eex:16: anonymous fn/2 in ExDebugToolbar.ToolbarView."show/ecto/_queries.html"/1
        (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_debug_toolbar) web/templates/toolbar/show/ecto/_queries.html.eex:13: anonymous fn/1 in ExDebugToolbar.ToolbarView."show/ecto/_queries.html"/1
        (ex_debug_toolbar) lib/ex_debug_toolbar.ex:118: ExDebugToolbar.record_event/3
        (ex_debug_toolbar) web/templates/toolbar/show/_ecto.html.eex:13: anonymous fn/1 in ExDebugToolbar.ToolbarView."show/_ecto.html"/1
        (ex_debug_toolbar) lib/ex_debug_toolbar.ex:118: ExDebugToolbar.record_event/3
        (ex_debug_toolbar) web/templates/toolbar/show.html.eex:18: anonymous fn/1 in ExDebugToolbar.ToolbarView."show.html"/1
        (ex_debug_toolbar) lib/ex_debug_toolbar.ex:118: ExDebugToolbar.record_event/3
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/view.ex:339: Phoenix.View.render_to_string/3
        (ex_debug_toolbar) web/channels/toolbar_channel.ex:39: ExDebugToolbar.ToolbarChannel.build_payload/1
        (ex_debug_toolbar) web/channels/toolbar_channel.ex:13: ExDebugToolbar.ToolbarChannel.join/3
        (phoenix) lib/phoenix/channel/server.ex:188: Phoenix.Channel.Server.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Please let me know if there's anything I can do to help narrow this down (I would have had a look at the code itself but I have a meeting shortly).

**Comment by kagux** [comment]
@Teifion, thanks for taking your time to test!
Could you post your `mix.exs` and `mix.lock` files please?

**Comment by Teifion** [comment]
Sure thing: https://gist.github.com/Teifion/f768abe03d2317a4225fd0515c19b2aa

**Comment by kagux** [comment]
@Teifion, thanks!
It looks like an issue caused by ecto log not having all timings set, which wasn't handled properly.
I've pushed an update, could you give it a go?

**Comment by Teifion** [comment]
It's working what appears to be perfectly! (I pointed to the github repo as I figured hex.pm wasn't updated yet).

Thanks!

**Comment by kagux** [comment]
great! thanks again, @Teifion !
btw, it is published on hex
